### ISSUE TITLE
What policy does Revoke STS require?

### ISSUE THREAD

**Issue by tleyden** [ThreatResponse/aws_ir_plugins#14]
As a follow-up from the [keynuker reddit thread](https://www.reddit.com/r/aws/comments/734lof/keynuker_nuke_aws_keys_accidentally_leaked_to/), I was wondering what policy this requires to run? 

Currently keynuker requires these permissions:

- iam:DeleteAccessKey
- iam:ListAccessKeys
- iam:ListUsers

**Comment by jparr** [comment]
We currently have the entire responder role here: https://github.com/ThreatResponse/aws_ir/blob/master/cloudformation/responder-role.yml

It works by putting in an inline policy so I think it is:

iam:AttachRolePolicy
iam:AttachUserPolicy
iam:DetachRolePolicy
iam:DetachUserPolicy
iam:CreatePolicy
iam:PutRolePolicy
iam:PutUserPolicy

Not sure about these ones: @andrewkrug will chime in but he's traveling.
iam:UpdateAccessKey
iam:UpdateUser

**Comment by tleyden** [comment]
Ok thanks!
